# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Logadarrshini's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Logadarrshini Kandaraj
headline: Welcome to my portfolio!
description: >-
  I am a Year 2 Robotics Systems Engineering student at the Singapore Institute of Technology and have been working with robotics and embedded systems over the past year.
  I enjoy working on projects where hardware and software come together and have gained experience with STM32 microcontrollers, the Propeller 1 board, programming in C, C++ and Python, as well as 3D modeling and mechanical design using SolidWorks.
  I also implemented autonomous navigation on the Agilex LIMO robot using ROS 1 (Melodic) during my last trimester as a year 1 student. Through this project, I gained further experience in system integration, testing, and troubleshooting.
  I enjoy learning by building and experimenting and am always looking for opportunities to grow as an engineer!


 

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: ./assets/resume/K.Logadarrshini_Resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: logadarrshini-kandaraj    # https://www.linkedin.com/in/{your url slug} 
  github: darrshini    # https://github.com/{your url slug}  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Programming
    tools:
    - C
    - C++
    - Python
    - Spin
  - category: 3D Modeling
    tools:
    - Solidworks
    - Fusion 360 (Autodesk)
  - category: Prototyping
    tools:
    - Fused Deposition Modeling (FDM) 3D printing
    - Breadboarding for circuit testing
  - category: Robot Operating System
    tools:
    - ROS 1 (Melodic)
    - RViz
    - SLAM integration (GMapping, RTAB-Map)
    - move_base for autonomous navigation
    - Costmap configuration (local & global)
    - Sensor integration ( LIDAR, depth cameras such as Orbbec)






# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/mdkdanpe



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
# ACTIVE PURPLE THEME (uncommented)
colors:
  text: "#333333"                
  border: "#c9a8f5"                
  link: "#7b2cbf"                  
  highlight: "#5a189a"            
  background: "#f9f6ff"             
  light_background: "#f3e5ff"       


# COMMENTED-OUT THEME OPTIONS (for future reference)
# basic theme:
#   text: "#1a1c20"
#   border: "#ddd"
#   link: "#4a76ee"
#   highlight: "#0c0cf2"
#   background: "#ffffff"
#   light_background: "#f3f5fb"
  
# mint theme:
#   text: "#2c3333"
#   border: "#e0f2ef"
#   link: "#40b3a2"
#   highlight: "#2a9d8f"
#   background: "#f7fbfa"
#   light_background: "#f0f9f7"
  
# lemon theme:
#   text: "#2d2926"
#   border: "#f7f3e3"
#   link: "#ffc94d"
#   highlight: "#ffb800"
#   background: "#fffdf5"
#   light_background: "#fff9e6"
  
# pink theme:
#   text: "#2d2d2d"
#   border: "#f8e2e2"
#   link: "#ff8fa3"
#   highlight: "#ff4d6d"
#   background: "#fff8f8"
#   light_background: "#fff5f6"





#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
